name: validation

# on:
#   pull_request:
#     paths:
#       - 'blockchain-client/terraform/**'
#   push:
#     branches:
#       - main
#   workflow_dispatch:

jobs:
  validate-infra:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: blockchain-client/terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: blockchain-client/terraform

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: blockchain-client/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
